# used in local development
name: "its"

services:
  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  docling:
    image: ghcr.io/docling-project/docling-serve-cpu:latest
    container_name: docling
    ports:
      - "5001:5001"
    restart: always
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
