name: "its"

services:
  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend/app:/usr/src/app
  #   depends_on:
  #     - db

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
  #       - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
