"""Add indexes to Chunk table

Revision ID: 0b8708325048
Revises: a84a79600dc6
Create Date: 2025-11-11 20:25:10.868924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0b8708325048"
down_revision: Union[str, Sequence[str], None] = "a84a79600dc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("useractivity")
    op.drop_table("taskversion")
    op.drop_table("taskmetrics")
    op.drop_table("eventlog")
    op.create_index("idx_chunk_document_id", "chunk", ["document_id"], unique=False)
    op.create_index(
        "idx_chunk_important", "chunk", ["document_id", "important"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_chunk_important", table_name="chunk")
    op.drop_index("idx_chunk_document_id", table_name="chunk")
    op.create_table(
        "eventlog",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "ANSWER_SUBMITTED",
                "TASK_MODIFIED",
                "TASK_DELETED",
                "TASK_CREATED",
                "PAGE_OPEN",
                "PAGE_CLOSE",
                "METRIC_UPDATE",
                name="eventtype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], name="eventlog_task_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="eventlog_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="eventlog_pkey"),
    )
    op.create_table(
        "taskmetrics",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "num_modifications", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("num_deletions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("num_acceptances", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("is_accepted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name="taskmetrics_task_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="taskmetrics_pkey"),
        sa.UniqueConstraint("task_id", name="taskmetrics_task_id_key"),
    )
    op.create_table(
        "taskversion",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("chunk_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("skill_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "answer_options",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("changed_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("change_reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "change_type",
            sa.VARCHAR(),
            server_default=sa.text("'modified'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_deleted_version",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["user.id"], name="taskversion_changed_by_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunk.id"], name="taskversion_chunk_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name="taskversion_skill_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="taskversion_task_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="taskversion_pkey"),
    )
    op.create_table(
        "useractivity",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("page_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("duration_sec", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="useractivity_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="useractivity_pkey"),
    )
    # ### end Alembic commands ###
