"""empty message

Revision ID: 132ce5366007
Revises: cdfe29122ff7
Create Date: 2025-10-07 13:17:51.658823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "132ce5366007"
down_revision: Union[str, Sequence[str], None] = "cdfe29122ff7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("report_task_id_fkey"), "report", type_="foreignkey")
    op.drop_constraint(op.f("report_unit_id_fkey"), "report", type_="foreignkey")
    op.create_foreign_key(
        None, "report", "task", ["task_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "report", "unit", ["unit_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "report", type_="foreignkey")
    op.drop_constraint(None, "report", type_="foreignkey")
    op.create_foreign_key(
        op.f("report_unit_id_fkey"), "report", "unit", ["unit_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("report_task_id_fkey"), "report", "task", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
