"""Add is_accepted and num_acceptances to TaskMetrics

Revision ID: 30fd8af28944
Revises: 7115a6db0acf
Create Date: 2025-11-04 23:10:23.247566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30fd8af28944"
down_revision: Union[str, Sequence[str], None] = "7115a6db0acf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_eventlog_task", table_name="eventlog")
    op.drop_index("idx_eventlog_type", table_name="eventlog")
    op.drop_table("eventlog")
    op.drop_table("taskmetrics")
    op.drop_index("idx_useractivity_user", table_name="useractivity")
    op.drop_table("useractivity")
    op.drop_table("useranswerlog")
    op.drop_index("idx_taskversion_task", table_name="taskversion")
    op.drop_table("taskversion")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskversion",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("chunk_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("skill_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "answer_options",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_deleted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("changed_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("change_reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["user.id"], name="fk_taskversion_changed_by_user"
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunk.id"], name="fk_taskversion_chunk_id_chunk"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name="fk_taskversion_skill_id_skill"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name="fk_taskversion_task_id_task",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="taskversion_pkey"),
    )
    op.create_index("idx_taskversion_task", "taskversion", ["task_id"], unique=False)
    op.create_table(
        "useranswerlog",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("result", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("time_spent_sec", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "submitted_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name="fk_useranswerlog_task_id_task",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_useranswerlog_user_id_user"
        ),
        sa.PrimaryKeyConstraint("id", name="useranswerlog_pkey"),
    )
    op.create_table(
        "useractivity",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("page_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("duration_sec", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_useractivity_user_id_user"
        ),
        sa.PrimaryKeyConstraint("id", name="useractivity_pkey"),
    )
    op.create_index("idx_useractivity_user", "useractivity", ["user_id"], unique=False)
    op.create_table(
        "taskmetrics",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "num_modifications",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "num_deletions",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "num_acceptances",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_updated",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name="fk_taskmetrics_task_id_task",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="taskmetrics_pkey"),
        sa.UniqueConstraint("task_id", name="uq_taskmetrics_task_id"),
    )
    op.create_table(
        "eventlog",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name="fk_eventlog_task_id_task",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_eventlog_user_id_user"
        ),
        sa.PrimaryKeyConstraint("id", name="eventlog_pkey"),
    )
    op.create_index("idx_eventlog_type", "eventlog", ["event_type"], unique=False)
    op.create_index("idx_eventlog_task", "eventlog", ["task_id"], unique=False)
    # ### end Alembic commands ###
