"""convert repo unit from m to n to m to 1

Revision ID: 6c7ebb16cf35
Revises: 70c05af27d10
Create Date: 2025-09-09 14:23:05.121414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c7ebb16cf35"
down_revision: Union[str, Sequence[str], None] = "70c05af27d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
