"""Adding logging models

Revision ID: 755bb2eadb1f
Revises: 0b8708325048
Create Date: 2025-11-15 23:23:16.359659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "755bb2eadb1f"
down_revision: Union[str, Sequence[str], None] = "0b8708325048"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define ENUMs explicitly
tasktype_enum = ENUM(
    "MULTIPLE_CHOICE",
    "FREE_TEXT",
    name="tasktype",
    create_type=False,  # We'll handle creation manually
)

pagetype_enum = ENUM(
    "TASKS",
    "DOCUMENTS",
    "SKILLS",
    "REPOSITORIES",
    "HOME",
    name="pagetype",
    create_type=False,
)

unittaskaction_enum = ENUM("ADDED", "REMOVED", name="unittaskaction", create_type=False)
resulttype_enum = ENUM(
    "CORRECT", "INCORRECT", "PARTIAL", name="resulttype", create_type=False
)
changetype_enum = ENUM(
    "QUESTION_UPDATE",
    "OPTION_ADDED",
    "OPTION_UPDATED",
    "OPTION_DELETED",
    "CORRECTNESS_CHANGED",
    "OTHER",
    name="changetype",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema with idempotent ENUM creation."""
    bind = op.get_bind()

    # === Create ENUMs only if they don't exist ===
    for enum in [
        tasktype_enum,
        pagetype_enum,
        unittaskaction_enum,
        resulttype_enum,
        changetype_enum,
    ]:
        enum_name = enum.name
        if not bind.dialect.has_type(bind, enum_name):
            enum.create(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userpagesession",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("page", pagetype_enum, nullable=False),
        sa.Column("entered_at", sa.DateTime(), nullable=False),
        sa.Column("left_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userpagesession_entered_at"),
        "userpagesession",
        ["entered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userpagesession_user_id"), "userpagesession", ["user_id"], unique=False
    )

    op.create_table(
        "taskstatistics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("total_created", sa.Integer(), nullable=False),
        sa.Column("total_deleted", sa.Integer(), nullable=False),
        sa.Column("total_modified", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_taskstatistics_repository_id"),
        "taskstatistics",
        ["repository_id"],
        unique=True,
    )

    op.create_table(
        "taskversion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("type", tasktype_enum, nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunk.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["skill_id"], ["skill.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "version"),
    )
    op.create_index(
        op.f("ix_taskversion_chunk_id"), "taskversion", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_taskversion_task_id"), "taskversion", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_taskversion_version"), "taskversion", ["version"], unique=False
    )

    op.create_table(
        "unittaskevent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("action", unittaskaction_enum, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unittaskevent_created_at"),
        "unittaskevent",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unittaskevent_task_id"), "unittaskevent", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_unittaskevent_unit_id"), "unittaskevent", ["unit_id"], unique=False
    )

    op.create_table(
        "answeroptionversion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("answer_option_id", sa.UUID(), nullable=True),
        sa.Column("task_version_id", sa.UUID(), nullable=True),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_option_id"], ["answeroption.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["task_version_id"], ["taskversion.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answeroptionversion_answer_option_id"),
        "answeroptionversion",
        ["answer_option_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_answeroptionversion_task_version_id"),
        "answeroptionversion",
        ["task_version_id"],
        unique=False,
    )

    op.create_table(
        "taskanswerevent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("answer_option_id", sa.UUID(), nullable=True),
        sa.Column("user_answer_text", sa.String(), nullable=True),
        sa.Column("result", resulttype_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_option_id"], ["answeroption.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_taskanswerevent_task_id"), "taskanswerevent", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_taskanswerevent_user_id"), "taskanswerevent", ["user_id"], unique=False
    )

    op.create_table(
        "taskchangeevent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("answer_option_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("change_type", changetype_enum, nullable=False),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("change_metadata", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_option_id"], ["answeroption.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_taskchangeevent_task_id"), "taskchangeevent", ["task_id"], unique=False
    )

    op.add_column(
        "task",
        sa.Column(
            "has_been_modified", sa.Boolean(), nullable=False, server_default="FALSE"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    op.drop_column("task", "has_been_modified")

    op.drop_index(op.f("ix_taskchangeevent_task_id"), table_name="taskchangeevent")
    op.drop_table("taskchangeevent")

    op.drop_index(op.f("ix_taskanswerevent_user_id"), table_name="taskanswerevent")
    op.drop_index(op.f("ix_taskanswerevent_task_id"), table_name="taskanswerevent")
    op.drop_table("taskanswerevent")

    op.drop_index(
        op.f("ix_answeroptionversion_task_version_id"), table_name="answeroptionversion"
    )
    op.drop_index(
        op.f("ix_answeroptionversion_answer_option_id"),
        table_name="answeroptionversion",
    )
    op.drop_table("answeroptionversion")

    op.drop_index(op.f("ix_unittaskevent_unit_id"), table_name="unittaskevent")
    op.drop_index(op.f("ix_unittaskevent_task_id"), table_name="unittaskevent")
    op.drop_index(op.f("ix_unittaskevent_created_at"), table_name="unittaskevent")
    op.drop_table("unittaskevent")

    op.drop_index(op.f("ix_taskversion_version"), table_name="taskversion")
    op.drop_index(op.f("ix_taskversion_task_id"), table_name="taskversion")
    op.drop_index(op.f("ix_taskversion_chunk_id"), table_name="taskversion")
    op.drop_table("taskversion")

    op.drop_index(op.f("ix_taskstatistics_repository_id"), table_name="taskstatistics")
    op.drop_table("taskstatistics")

    op.drop_index(op.f("ix_userpagesession_user_id"), table_name="userpagesession")
    op.drop_index(op.f("ix_userpagesession_entered_at"), table_name="userpagesession")
    op.drop_table("userpagesession")

    # Drop ENUMs only if they exist
    for enum in [
        tasktype_enum,
        pagetype_enum,
        unittaskaction_enum,
        resulttype_enum,
        changetype_enum,
    ]:
        enum_name = enum.name
        if bind.dialect.has_type(bind, enum_name):
            enum.drop(bind)
