"""Adding logging 

Revision ID: 92edd72fe1ad
Revises: 755bb2eadb1f
Create Date: 2025-11-16 17:04:41.769277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92edd72fe1ad'
down_revision: Union[str, Sequence[str], None] = '755bb2eadb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unittaskevent_created_at', table_name='unittaskevent')
    op.drop_index('ix_unittaskevent_task_id', table_name='unittaskevent')
    op.drop_index('ix_unittaskevent_unit_id', table_name='unittaskevent')
    op.drop_table('unittaskevent')
    op.drop_index('idx_chunk_document_id', table_name='chunk')
    op.drop_index('idx_chunk_important', table_name='chunk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chunk_important', 'chunk', ['document_id', 'important'], unique=False)
    op.create_index('idx_chunk_document_id', 'chunk', ['document_id'], unique=False)
    op.create_table('unittaskevent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('ADDED', 'REMOVED', name='unittaskaction'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='unittaskevent_task_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='unittaskevent_unit_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='unittaskevent_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='unittaskevent_pkey')
    )
    op.create_index('ix_unittaskevent_unit_id', 'unittaskevent', ['unit_id'], unique=False)
    op.create_index('ix_unittaskevent_task_id', 'unittaskevent', ['task_id'], unique=False)
    op.create_index('ix_unittaskevent_created_at', 'unittaskevent', ['created_at'], unique=False)
    # ### end Alembic commands ###
