"""Add task versioning and answer logging

Revision ID: a84a79600dc6
Revises: 7dc6becbefd6
Create Date: 2025-11-05 17:58:45.682907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a84a79600dc6"
down_revision: Union[str, Sequence[str], None] = "7dc6becbefd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "taskversion",
        sa.Column(
            "change_type",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="modified",
            nullable=False,
        ),
    )
    op.add_column(
        "taskversion",
        sa.Column(
            "is_deleted_version", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("taskversion", "is_deleted_version")
    op.drop_column("taskversion", "change_type")
    # ### end Alembic commands ###
