"""Initial database schema

Revision ID: b10f3e70a1a2
Revises:
Create Date: 2025-08-04 10:45:05.968046

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b10f3e70a1a2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
