"""empty message

Revision ID: b15add050986
Revises: 95f4da89fc59
Create Date: 2025-09-01 11:13:43.680311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b15add050986"
down_revision: Union[str, Sequence[str], None] = "95f4da89fc59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("skill_name_key"), "skill", type_="unique")
    op.drop_index(op.f("ix_skill_name"), table_name="skill")
    op.create_index(op.f("ix_skill_name"), "skill", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skill_name"), table_name="skill")
    op.create_index(op.f("ix_skill_name"), "skill", ["name"], unique=False)
    op.create_unique_constraint(
        op.f("skill_name_key"), "skill", ["name"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
