"""final Tasks ChangeType

Revision ID: c63817311ded
Revises: a65f15891825
Create Date: 2025-11-18 13:46:13.527948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63817311ded'
down_revision: Union[str, Sequence[str], None] = 'a65f15891825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE changetype ADD VALUE 'MODIFIED'")
    op.execute("ALTER TYPE changetype ADD VALUE 'DELETED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
