"""Add event logging and analytics tables

Revision ID: cdcff104e1d3
Revises: 132ce5366007
Create Date: 2025-11-04 13:42:28.074337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdcff104e1d3"
down_revision: Union[str, Sequence[str], None] = "132ce5366007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create EventLog table
    op.create_table(
        "eventlog",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("task_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="fk_eventlog_task_id_task"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_eventlog_user_id_user"
        ),
    )
    op.create_index("idx_eventlog_type", "eventlog", ["event_type"], unique=False)
    op.create_index("idx_eventlog_task", "eventlog", ["task_id"], unique=False)

    # Create TaskVersion table (Shadow Modification)
    op.create_table(
        "taskversion",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("chunk_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("skill_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "answer_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("changed_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["user.id"], name="fk_taskversion_changed_by_user"
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunk.id"], name="fk_taskversion_chunk_id_chunk"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name="fk_taskversion_skill_id_skill"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="fk_taskversion_task_id_task"
        ),
    )
    op.create_index("idx_taskversion_task", "taskversion", ["task_id"], unique=False)

    # Create TaskMetrics table
    op.create_table(
        "taskmetrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("num_modifications", sa.Integer(), server_default="0", nullable=True),
        sa.Column("num_deletions", sa.Integer(), server_default="0", nullable=True),
        sa.Column("num_acceptances", sa.Integer(), server_default="0", nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="fk_taskmetrics_task_id_task"
        ),
        sa.UniqueConstraint("task_id", name="uq_taskmetrics_task_id"),
    )

    # Create UserActivity table
    op.create_table(
        "useractivity",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page_name", sa.String(), nullable=False),
        sa.Column(
            "start_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_useractivity_user_id_user"
        ),
    )
    op.create_index("idx_useractivity_user", "useractivity", ["user_id"], unique=False)

    # Create UserAnswerLog table
    op.create_table(
        "useranswerlog",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("time_spent_sec", sa.Integer(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="fk_useranswerlog_task_id_task"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="fk_useranswerlog_user_id_user"
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("useranswerlog")
    op.drop_table("useractivity")
    op.drop_table("taskmetrics")
    op.drop_index("idx_taskversion_task", table_name="taskversion")
    op.drop_table("taskversion")
    op.drop_index("idx_eventlog_task", table_name="eventlog")
    op.drop_index("idx_eventlog_type", table_name="eventlog")
    op.drop_table("eventlog")
    # ### end Alembic commands ###
