name: Build and Push Docker

on:
  push:
    branches: ["main", "live"]
  workflow_dispatch:
    inputs:
      force_rebuild_frontend:
        description: "Force rebuild frontend (ignores change detection)"
        required: false
        default: "false"
        type: boolean
      force_rebuild_backend:
        description: "Force rebuild backend (ignores change detection)"
        required: false
        default: "false"
        type: boolean
      skip_tests:
        description: "Skip deployment tests"
        required: false
        default: "false"
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Log in to GHCR
        if: steps.changes.outputs.frontend == 'true' || github.event.inputs.force_rebuild_frontend == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Frontend Image
        if: steps.changes.outputs.frontend == 'true' || github.event.inputs.force_rebuild_frontend == 'true'
        run: |
          docker build ./frontend --file ./frontend/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:${{ github.ref_name }} \
            --build-arg NUXT_PUBLIC_API_BASE=https://tutor.ethz.ch/api \

      - name: Push frontend Image
        if: steps.changes.outputs.frontend == 'true' || github.event.inputs.force_rebuild_frontend == 'true'
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:${{ github.ref_name }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'

      - name: Log in to GHCR
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_rebuild_backend == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend Image
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_rebuild_backend == 'true'
        run: |
          docker build ./backend --file ./backend/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:${{ github.ref_name }} \

      - name: Push backend Image
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_rebuild_backend == 'true'
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:${{ github.ref_name }}

  # Deployment testing job
  test-deployment:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/live') && github.event.inputs.skip_tests != 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker images
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:${{ github.ref_name }}
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:${{ github.ref_name }}

      - name: Create test environment file
        run: |
          cat > .env.test << EOF
          DB_USER=test_user
          DB_PASSWORD=test_password
          DB_NAME=test_db
          DB_HOST=localhost
          DB_PORT=5432
          CORS_ORIGINS=http://localhost:3000,http://localhost:80
          TEST_DEPLOYMENT=true
          GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}
          GITHUB_REF_NAME=${{ github.ref_name }}
          EOF

      - name: Start test containers
        run: |
          # Start database first
          docker run -d --name test-db \
            -p 5432:5432 \
            -e POSTGRES_USER=test_user \
            -e POSTGRES_PASSWORD=test_password \
            -e POSTGRES_DB=test_db \
            postgres:17-alpine

          # Wait for database to be ready
          echo "⏳ Waiting for PostgreSQL to be ready..."
          sleep 15

          # Check if database is accepting connections
          echo "🔍 Checking database connectivity..."
          docker exec test-db pg_isready -U test_user -d test_db -h localhost || echo "⚠️  Database may not be fully ready yet"

          # Start backend with additional logging
          echo "🚀 Starting backend container..."
          docker run -d --name test-backend \
            --network host \
            --env-file .env.test \
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:${{ github.ref_name }}

          # Give backend more time to initialize
          echo "⏳ Waiting for backend to initialize..."
          sleep 20

          # Check if backend container is running
          if docker ps | grep -q test-backend; then
            echo "✅ Backend container is running"
            # Show backend logs to help debug
            echo "📋 Backend container logs (last 20 lines):"
            docker logs test-backend 2>&1 | tail -20 || echo "No logs available yet"
          else
            echo "❌ Backend container failed to start"
            docker ps -a | grep test-backend || echo "Backend container not found"
          fi

          # Start frontend
          echo "🚀 Starting frontend container..."
          docker run -d --name test-frontend \
            -p 3000:80 \
            -e NUXT_PUBLIC_API_BASE=http://localhost:8000 \
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:${{ github.ref_name }}

          # Wait for services to start
          echo "⏳ Final wait for services to be ready..."
          sleep 10

      - name: Run deployment health checks
        run: |
          chmod +x ./scripts/health-check.sh
          BACKEND_URL=http://localhost:8000 FRONTEND_URL=http://localhost:3000 ./scripts/health-check.sh

      - name: Cleanup test containers
        if: always()
        run: |
          docker stop test-frontend test-backend test-db || true
          docker rm test-frontend test-backend test-db || true
